name: publish

on:
  push:
    branches:
      - main

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  publish-shiny_app_example:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: xingyaoc
        password:   ${{ secrets.GITHUB_TOKEN }} 

    - name: Build the Shiny App Example Docker image
      run: |
        docker build . --tag ghcr.io/xingyaoc/shiny_app_example:latest
        docker push ghcr.io/xingyaoc/shiny_app_example:latest


    - name: Executing Remote Ssh Command to Pull Docker Image to shiny-apps
      uses: appleboy/ssh-action@master
      with:
        host: 158.101.15.103
        username: opc
        key: ${{ secrets.KEY }}
        port: 22
        script: docker pull ghcr.io/xingyaoc/shiny_app_example:latest